apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-app
  labels:
    app: book-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-app
  template:
    metadata:
      labels:
        app: book-app
    spec:
      containers:
        - name: book-app
          image: quay.io/kiranpoli/gdas:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: QUARKUS_PROFILE
              value: prod


