apiVersion: v1
kind: Pod
metadata:
  name: pvc-test
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep","360"]
      volumeMounts:
        - mountPath: /data
          name: maven-cache
  volumes:
    - name: maven-cache
      persistentVolumeClaim:
        claimName: maven-cache-pvc
